alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: null
global:
  evaluation_interval: 20s
  scrape_interval: 20s
rule_files: null
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - 192.168.1.11:9090
- job_name: node_exporter
  static_configs:
  - labels:
      foo: bar
    targets:
    - 127.0.0.1:9100
- job_name: redis_exporter
  static_configs:
  - labels:
      foo: bar
    targets:
    - 127.0.0.1:6379
